# Netlify configuration file

[build]
  # Base directory
  base = "/"
  
  # No build command needed for static site
  # command = ""
  
  # Directory to publish (the root directory in this case)
  publish = "/"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    # Allow embedding from any domain
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    
    # CORS headers to allow embedding
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    
    # Cache control for static assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/samples/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
